
enum ServiceMethods{
  LOGIN,
  GETALLSELLERSFORUNIT,
  REACTIVATEUSER,
  DEACTIVATEUSER,
  UPLOADID,
  GETPAYMENTMETHOD,
  GETPAYMENTSTATUS,
  PAYMENTWINNINGBILLS,
  DETAILEDBILLINFO,
  GETALLPAYMENTSFORUNIT,
  GETALLLOTLIST,
  GETALLSALESREPORTLIST,
  GETPAYMENTINFO,
  MAKE_PAYMENT,
  PRESETTLEMENT,
}